chore: update release workflow to fetch tags and validate version tags

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -27,7 +27,11 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0  # Required for svu to work properly with git history
-        
+          fetch-tags: true
+      - name: Show git tags
+        run: |
+          git tag --sort=-version:refname | head -5
+
       - name: Setup Go
         uses: actions/setup-go@v5
         with:
@@ -61,7 +65,6 @@ jobs:
           just release ${{ inputs.version_type }}
           version=$(git describe --tags --abbrev=0)
           echo "version=${version}" >> $GITHUB_OUTPUT
-        
       - name: Push version changes
         run: |
           # Set a new remote URL using HTTPS with the github token
@@ -86,11 +89,25 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Required for git describe to work properly with git history
+          fetch-tags: true
+
+      - name: Validate git tags
+        run: |
+          # if not, the version in the output of needs.version.outputs.version is not a tag
+          # and the release should fail.
+          if [ "${{ needs.version.outputs.version }}" != "$(git describe --tags --abbrev=0)" ]; then
+            echo "Error: The version in the output of needs.version.outputs.version is not a tag"
+            echo "Expected: ${{ needs.version.outputs.version }}"
+            echo "Actual: $(git describe --tags --abbrev=0)"
+            exit 1
+          fi
         
       - name: Setup Go
-        uses: actions/setup-go@v4
+        uses: actions/setup-go@v5
         with:
-          go-version: '1.21'
+          go-version: '1.24.3'
           
       - name: Install just
         uses: taiki-e/install-action@just
